SELECT coiid,
       chiid,
       hzname,
       hzdept_r,
       hzdepb_r,
       texture,
       fragvoltot_l,
       fragvoltot_r,
       fragvoltot_h,
       sandtotal_l,
       sandtotal_r,
       sandtotal_h,
       silttotal_l,
       silttotal_r,
       silttotal_h,
       claytotal_l,
       claytotal_r,
       claytotal_h,
       om_l,
       om_r,
       om_h,
       structgrpname,
       dbthirdbar_l,
       dbthirdbar_r,
       dbthirdbar_h,
       ksat_l,
       ksat_r,
       ksat_h,
       awc_l,
       awc_r,
       awc_h,
       lep_l,
       lep_r,
       lep_h,
       ll_l,
       ll_r,
       ll_h,
       pi_l,
       pi_r,
       pi_h,
       sieveno4_l,
       sieveno4_r,
       sieveno4_h,
       sieveno10_l,
       sieveno10_r,
       sieveno10_h,
       sieveno40_l,
       sieveno40_r,
       sieveno40_h,
       sieveno200_l,
       sieveno200_r,
       sieveno200_h,
       sar_l,
       sar_r,
       sar_h,
       ec_l,
       ec_r,
       ec_h,
       cec7_l,
       cec7_r,
       cec7_h,
       sumbases_l,
       sumbases_r,
       sumbases_h,
       ecec_l,
       ecec_r,
       ecec_h,
       ph1to1h2o_l,
       ph1to1h2o_r,
       ph1to1h2o_h,
       ph01mcacl2_l,
       ph01mcacl2_r,
       ph01mcacl2_h,
       caco3_l,
       caco3_r,
       caco3_h,
       kffact,
       kwfact,
       aashind_l,
       aashind_r,
       aashind_h
FROM   component_view_1 co
       LEFT OUTER JOIN chorizon_view_1 ch
                    ON ch.coiidref = co.coiid
       LEFT OUTER JOIN chtexturegrp_view_1 cht
                    ON cht.chiidref = ch.chiid
                       AND cht.rvindicator = 1
       LEFT OUTER JOIN chstructgrp_view_1 chs
                    ON chs.chiidref = ch.chiid
                       AND chs.rvindicator = 1
       -- why is this here?
       INNER JOIN datamapunit_view_1 dmu
               ON dmu.dmuiid = co.dmuiidref
ORDER  BY dmudesc,
          comppct_r DESC,
          compname ASC,
          hzdept_r ASC; 
		  